spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_manydemo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
